# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Bentian.ERPBridge
PackageVersion: 0.3.5
InstallerLocale: es-ES
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
ProductCode: '{8B23F40E-3F15-4D1E-97C5-C36B286E9559}_is1'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- ProductCode: '{8B23F40E-3F15-4D1E-97C5-C36B286E9559}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://bridge.cristianjm.com/releases/v0.3.5/Bentian-Setup-v0.3.5.exe
  InstallerSha256: B68BA9B3E3C5B62322AE8164384C301D51A8700FEE44EF15EBB87D7D4D77D282
ManifestType: installer
ManifestVersion: 1.12.0
